---
- name: "Setup"
  hosts: all
  gather_subset: env
  vars_files:
    - ../inventory/group_vars/all.yml

  handlers:
    - name: "Reloading SystemD Daemon"
      ansible.builtin.systemd_service:
        daemon_reload: true
        scope: user
      listen: user-daemon-reload

    - name: "SystemD Reset Failed"
      ansible.builtin.shell:
        cmd: systemctl --user reset-failed
      listen: user-reset-failed

  tasks:
    - name: "Install Block"
      tags:
        - install
        - never
      block:
        - name: "Including Install Tasks"
          ansible.builtin.include_tasks:
            file: ./install.yml

    - name: "Uninstall Block"
      tags:
        - uninstall
        - never
      block:
        - name: "Including Uninstall Tasks"
          ansible.builtin.include_tasks:
            file: ./uninstall.yml

    - name: "Enable Timer Block"
      tags:
        - enable-timers
        - never
      block:
        - name: "Including Enable Tasks"
          ansible.builtin.include_tasks:
            file: ./enable.yml

    - name: "Disable Timer Block"
      tags:
        - disable-timers
        - never
      block:
        - name: "Including Disable Tasks"
          ansible.builtin.include_tasks:
            file: ./disable.yml
