---
- name: "Including Disable Punch Timers"
  ansible.builtin.include_tasks:
    file: ./disable.yml

- name: "Removing punch Installed Files"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ systemd_dir }}/punch.service"
    - "{{ systemd_dir }}/punch.timer"
    - "{{ install_dir }}/punch.sh"
    - "{{ install_dir }}/punch.conf"
  notify:
    - user-daemon-reload
    - user-reset-failed

- name: "Flusing Handlers"
  ansible.builtin.meta: flush_handlers
